openapi: 3.0.1
info:
  title: monster-giant-owl
  x-cortex-tag: monster-giant-owl
x-cortex-custom-data:
  alignment: chaotic-good
  source: dnd-5e
x-cortex-owners:
- email: bestiary@dnd.com
x-cortex-tag: monster-giant-owl
x-cortex-type: monster
